framework:
    mailer:
         dsn: '%env(MAILER_DSN)%'

#framework:
    #mailer:
        #dsn: '%env(MAILER_DSN)%'
        #transport: 'sendmail'
        #sendmail:
            #path: '/usr/sbin/sendmail'
            #arguments:
                #- '-i'
                #- '-t'


       
      
    