controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_register:
    path: /register
    controller: App\Controller\RegistrationController::register

download_cv:
    path: /annonces/download_cv/{filename}
    controller: App\Controller\AnnonceController::downloadCV    
    requirements:
        filename: '.+'
            